### ISSUE TITLE
0.5.1 doesn't run tests

### ISSUE THREAD

**Issue by Laboratory** [mad-eye/meteor-mocha-web#117]
Hello, after update on version 0.5.1 from 0.5.0 my test doesn't runs

``` bash
$ VELOCITY_DEBUG=true  meteor --test
I20141225-15:27:54.729(3)? [velocity] adding velocity core
I20141225-15:27:54.767(3)? [velocity] Not adding mirror-registrar because NODE_ENV is development and IS_MIRROR is false
I20141225-15:27:54.767(3)? [node-soft-mirror] adding server code
I20141225-15:27:54.767(3)? [velocity] Velocity not started. Queueing func
I20141225-15:27:54.767(3)? [velocity] Server startup
I20141225-15:27:54.767(3)? [velocity] app dir /Users/Laboratory/projects/node/v/a/meteor-app
I20141225-15:27:54.768(3)? [velocity] config = {
I20141225-15:27:54.768(3)?   "mocha": {
I20141225-15:27:54.768(3)?     "regex": "mocha/.+\\.(js|coffee|litcoffee|coffee\\.md)$",
I20141225-15:27:54.768(3)?     "name": "mocha",
I20141225-15:27:54.768(3)?     "_regexp": {}
I20141225-15:27:54.768(3)?   }
I20141225-15:27:54.768(3)? }
I20141225-15:27:54.768(3)? [velocity] resetting the world
I20141225-15:27:54.769(3)? [velocity] frameworks with disable auto reset: []
I20141225-15:27:54.769(3)? [velocity-node-mirror] Server restarted.
I20141225-15:27:54.769(3)? [velocity-node-mirror] Aggressively restarting all mirrors
I20141225-15:27:54.770(3)? [node-soft-mirror]: LongRunningChildProcess.constructor(taskName=mocha)
I20141225-15:27:54.770(3)? [node-soft-mirror]: LongRunningChildProcess.readPid()
I20141225-15:27:54.770(3)? [node-soft-mirror]: LongRunningChildProcess.readPid returns 3040
I20141225-15:27:54.779(3)? [node-soft-mirror]: LongRunningChildProcess.isRunning returns false
I20141225-15:27:54.779(3)? [node-soft-mirror] Mirror for framework mocha is not running
I20141225-15:27:54.779(3)? [node-soft-mirror] Aggressively reload client
=> Started your app.

=> App running at: http://localhost:3000/
I20141225-15:27:54.818(3)? [velocity] Target framework for tests/mocha/server/charts/chartList.coffee is mocha
I20141225-15:27:54.818(3)? [velocity] Target framework for tests/mocha/server/charts/chartMethods.coffee is mocha
I20141225-15:27:54.819(3)? [velocity] Target framework for tests/mocha/server/dashboard/Dashboard.coffee is mocha
I20141225-15:27:54.820(3)? [velocity] Target framework for tests/mocha/server/dashboard/DashboardList.coffee is mocha
I20141225-15:27:54.820(3)? [velocity] Target framework for tests/mocha/server/dashboard/common.coffee is mocha
I20141225-15:27:54.821(3)? [velocity] Target framework for tests/mocha/server/dashboard/methods.coffee is mocha
I20141225-15:27:54.821(3)? [velocity] Target framework for tests/mocha/server/datasources/datasourcesMethods.coffee is mocha
I20141225-15:27:54.822(3)? [velocity] Target framework for tests/mocha/server/queryBuilder/QBCollection.coffee is mocha
I20141225-15:27:54.823(3)? [velocity] Target framework for tests/mocha/server/queryBuilder/MongoQuery.coffee is mocha
I20141225-15:27:54.831(3)? [velocity] Target framework for tests/mocha/server/queryBuilder/QBMethods.coffee is mocha
I20141225-15:27:54.832(3)? [velocity] File scan complete, now watching /tests
I20141225-15:27:54.832(3)? [velocity] Triggering queued startup functions
I20141225-15:27:54.843(3)? [proxy-package-sync] Test file added tests/mocha/server/charts/chartList.coffee
I20141225-15:27:54.848(3)? [proxy-package-sync] Test file added tests/mocha/server/charts/chartMethods.coffee
I20141225-15:27:54.848(3)? [proxy-package-sync] Test file added tests/mocha/server/dashboard/Dashboard.coffee
I20141225-15:27:54.848(3)? [proxy-package-sync] Test file added tests/mocha/server/dashboard/DashboardList.coffee
I20141225-15:27:54.848(3)? [proxy-package-sync] Test file added tests/mocha/server/dashboard/common.coffee
I20141225-15:27:54.848(3)? [proxy-package-sync] Test file added tests/mocha/server/dashboard/methods.coffee
I20141225-15:27:54.848(3)? [proxy-package-sync] Test file added tests/mocha/server/datasources/datasourcesMethods.coffee
I20141225-15:27:54.848(3)? [proxy-package-sync] Test file added tests/mocha/server/queryBuilder/QBCollection.coffee
I20141225-15:27:54.849(3)? [proxy-package-sync] Test file added tests/mocha/server/queryBuilder/MongoQuery.coffee
I20141225-15:27:54.850(3)? [proxy-package-sync] Test file added tests/mocha/server/queryBuilder/QBMethods.coffee
I20141225-15:27:54.861(3)? [velocity] Mirror requested { framework: 'mocha',
I20141225-15:27:54.861(3)?   rootUrlPath: '?mocha=true',
I20141225-15:27:54.861(3)?   port: 5000,
I20141225-15:27:54.861(3)?   host: 'http://localhost:5000/',
I20141225-15:27:54.861(3)?   rootUrl: 'http://localhost:5000/?mocha=true' }
I20141225-15:27:54.862(3)? [node-soft-mirror]: LongRunningChildProcess.isRunning returns false
.....
I20141225-15:27:54.868(3)? [node-soft-mirror]: LongRunningChildProcess.isRunning returns false
I20141225-15:27:54.868(3)? [node-soft-mirror]: /Users/Laboratory/projects/node/v/a/meteor-app/.meteor/local/build/programs/server/assets/packages/velocity_node-soft-mirror/lib/spawnScript.js
I20141225-15:27:54.868(3)? [node-soft-mirror]: The pid of the main Meteor app process is 3134
I20141225-15:27:54.869(3)? [node-soft-mirror]: LongRunningChildProcess.spawn is spawning 'node'
I20141225-15:27:54.869(3)? [node-soft-mirror]: LongRunningChildProcess._setPid(pid=3155)
I20141225-15:27:54.869(3)? [node-soft-mirror]: Saving mocha pid 3155 to /Users/Laboratory/projects/node/v/a/meteor-app/.meteor/local/run/mocha.pid
I20141225-15:27:54.869(3)? [velocity-node-mirror] Mirror process forked with pid 3155
I20141225-15:27:54.905(3)? [velocity-mirror] Spawn script arguments:
I20141225-15:27:54.905(3)?
I20141225-15:27:54.905(3)? [velocity-mirror] parentPid: 3134
I20141225-15:27:54.906(3)? command: node
I20141225-15:27:54.906(3)?
I20141225-15:27:54.906(3)? [velocity-mirror] commandArguments: [ '/Users/Laboratory/projects/node/v/a/meteor-app/.meteor/local/build/main.js' ]
I20141225-15:27:54.906(3)?
I20141225-15:27:55.052(3)? [proxy-package-sync] Checking if a new package.js needs to be written because {} undefined
I20141225-15:27:55.052(3)? [proxy-package-sync] Generating in-memory package.js
I20141225-15:27:55.053(3)? [proxy-package-sync] Fixture files list length:  0
I20141225-15:27:55.054(3)? [proxy-package-sync] Test files list length:  10
I20141225-15:27:55.054(3)? [proxy-package-sync] Test file will be included in mirror tests/mocha/server/charts/chartList.coffee
I20141225-15:27:55.054(3)? [proxy-package-sync] Test file will be included in mirror tests/mocha/server/charts/chartMethods.coffee
I20141225-15:27:55.054(3)? [proxy-package-sync] Test file will be included in mirror tests/mocha/server/dashboard/common.coffee
I20141225-15:27:55.054(3)? [proxy-package-sync] Test file will be included in mirror tests/mocha/server/dashboard/Dashboard.coffee
I20141225-15:27:55.055(3)? [proxy-package-sync] Test file will be included in mirror tests/mocha/server/dashboard/DashboardList.coffee
I20141225-15:27:55.055(3)? [proxy-package-sync] Test file will be included in mirror tests/mocha/server/dashboard/methods.coffee
I20141225-15:27:55.055(3)? [proxy-package-sync] Test file will be included in mirror tests/mocha/server/datasources/datasourcesMethods.coffee
I20141225-15:27:55.055(3)? [proxy-package-sync] Test file will be included in mirror tests/mocha/server/queryBuilder/MongoQuery.coffee
I20141225-15:27:55.055(3)? [proxy-package-sync] Test file will be included in mirror tests/mocha/server/queryBuilder/QBCollection.coffee
I20141225-15:27:55.055(3)? [proxy-package-sync] Test file will be included in mirror tests/mocha/server/queryBuilder/QBMethods.coffee
I20141225-15:27:55.066(3)? [proxy-package-sync] Comparing:
I20141225-15:27:55.069(3)? [proxy-package-sync] - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
I20141225-15:27:55.070(3)? [proxy-package-sync] - - - - - - - - - currentPackageJS: - - - - - - - - - - - - -
I20141225-15:27:55.070(3)? Package.describe({
I20141225-15:27:55.070(3)?  name: "velocity:test-proxy",
I20141225-15:27:55.071(3)?  summary: "Dynamically created package to expose test files to mirrors",
I20141225-15:27:55.071(3)?  version: "0.0.4",
I20141225-15:27:55.071(3)?  debugOnly: true
I20141225-15:27:55.072(3)? });
I20141225-15:27:55.072(3)?
I20141225-15:27:55.072(3)? Package.on_use(function (api) {
I20141225-15:27:55.072(3)?  api.use("coffeescript", ["client", "server"]);
I20141225-15:27:55.072(3)?  api.add_files("tests/mocha/server/charts/chartList.coffee",["server"]);
I20141225-15:27:55.072(3)?  api.add_files("tests/mocha/server/charts/chartMethods.coffee",["server"]);
I20141225-15:27:55.072(3)?  api.add_files("tests/mocha/server/dashboard/common.coffee",["server"]);
I20141225-15:27:55.072(3)?  api.add_files("tests/mocha/server/dashboard/Dashboard.coffee",["server"]);
I20141225-15:27:55.072(3)?  api.add_files("tests/mocha/server/dashboard/DashboardList.coffee",["server"]);
I20141225-15:27:55.073(3)?  api.add_files("tests/mocha/server/dashboard/methods.coffee",["server"]);
I20141225-15:27:55.073(3)?  api.add_files("tests/mocha/server/datasources/datasourcesMethods.coffee",["server"]);
I20141225-15:27:55.073(3)?  api.add_files("tests/mocha/server/queryBuilder/MongoQuery.coffee",["server"]);
I20141225-15:27:55.073(3)?  api.add_files("tests/mocha/server/queryBuilder/QBCollection.coffee",["server"]);
I20141225-15:27:55.073(3)?  api.add_files("tests/mocha/server/queryBuilder/QBMethods.coffee",["server"]);
I20141225-15:27:55.073(3)? });
I20141225-15:27:55.073(3)? [proxy-package-sync] - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
I20141225-15:27:55.073(3)? [proxy-package-sync] - - - - - - - - - generatedPackageJsContent - - - - - - - - -
I20141225-15:27:55.074(3)? Package.describe({
I20141225-15:27:55.074(3)?  name: "velocity:test-proxy",
I20141225-15:27:55.074(3)?  summary: "Dynamically created package to expose test files to mirrors",
I20141225-15:27:55.074(3)?  version: "0.0.4",
I20141225-15:27:55.074(3)?  debugOnly: true
I20141225-15:27:55.074(3)? });
I20141225-15:27:55.074(3)?
I20141225-15:27:55.074(3)? Package.on_use(function (api) {
I20141225-15:27:55.074(3)?  api.use("coffeescript", ["client", "server"]);
I20141225-15:27:55.074(3)?  api.add_files("tests/mocha/server/charts/chartList.coffee",["server"]);
I20141225-15:27:55.075(3)?  api.add_files("tests/mocha/server/charts/chartMethods.coffee",["server"]);
I20141225-15:27:55.075(3)?  api.add_files("tests/mocha/server/dashboard/common.coffee",["server"]);
I20141225-15:27:55.075(3)?  api.add_files("tests/mocha/server/dashboard/Dashboard.coffee",["server"]);
I20141225-15:27:55.075(3)?  api.add_files("tests/mocha/server/dashboard/DashboardList.coffee",["server"]);
I20141225-15:27:55.075(3)?  api.add_files("tests/mocha/server/dashboard/methods.coffee",["server"]);
I20141225-15:27:55.075(3)?  api.add_files("tests/mocha/server/datasources/datasourcesMethods.coffee",["server"]);
I20141225-15:27:55.075(3)?  api.add_files("tests/mocha/server/queryBuilder/MongoQuery.coffee",["server"]);
I20141225-15:27:55.076(3)?  api.add_files("tests/mocha/server/queryBuilder/QBCollection.coffee",["server"]);
I20141225-15:27:55.076(3)?  api.add_files("tests/mocha/server/queryBuilder/QBMethods.coffee",["server"]);
I20141225-15:27:55.076(3)? });
I20141225-15:27:55.076(3)? [proxy-package-sync] - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
I20141225-15:27:55.076(3)? [proxy-package-sync] No changes to package.js file required
I20141225-15:27:55.330(3)? [velocity-mirror] [velocity] Mirror detected - Not adding velocity core
I20141225-15:27:55.330(3)?
I20141225-15:27:55.330(3)? [velocity-mirror] [velocity] Not adding mirror-registry because NODE_ENV is development  and IS_MIRROR is true
I20141225-15:27:55.331(3)? [velocity-mirror] Mirror is initializing...
I20141225-15:27:55.331(3)?
I20141225-15:27:55.374(3)? [velocity-mirror] SETUP GLOBALS
I20141225-15:27:55.374(3)?
I20141225-15:27:55.425(3)? [velocity-mirror] [proxy-package-sync] Mirror detected - Not adding code
I20141225-15:27:55.426(3)?
I20141225-15:27:55.429(3)? [velocity-mirror] [velocity-mirror] Mirror started. Connecting via DDP to parent
I20141225-15:27:55.429(3)?
I20141225-15:27:55.433(3)? [velocity-mirror] MOCHA-WEB MIRROR LISTENING AT http://localhost:5000/?mocha=true
I20141225-15:27:55.433(3)?
I20141225-15:27:55.433(3)? [velocity-mirror] PARENT URL http://localhost:3000/
I20141225-15:27:55.433(3)?
I20141225-15:27:55.479(3)? [velocity-mirror] [velocity] Mirror connected to parent. Registering mirror...
I20141225-15:27:55.479(3)?
I20141225-15:27:55.481(3)? [velocity] Mirror registered. Handshaking with mirror...
I20141225-15:27:55.796(3)? [velocity] Connected to mirror, setting state to ready { framework: 'mocha',
I20141225-15:27:55.796(3)?   port: '5000',
I20141225-15:27:55.796(3)?   host: 'http://localhost:5000/' }
I20141225-15:27:55.798(3)? [velocity-mirror] [velocity-mirror] Mirror is ready.
```

**Comment by rissem** [comment]
Hi @Laboratory. Sorry for not replying to this sooner. I just updated the example in https://github.com/meteor-velocity/velocity-examples to 0.5.1 and things worked. I did have to upgrade the node installed on my system so it was > 0.10.33.

Try running with `DEBUG=1 VELOCITY_DEBUG=1 VELOCITY_DEBUG_MIRROR=1 meteor` and maybe you'll get a more helpful error message.

Hope this helps.

**Comment by Laboratory** [comment]
Hi, sorry. My tests don't run. But I see in logs files which were added

**Comment by mquandalle** [comment]
I encounter the same bug. I guess the line `Mirror for framework mocha is not running ` is something wrong?

**Comment by Sanjo** [comment]
Maybe the mirror log `.meteor/local/log/` contains something useful.

**Comment by mquandalle** [comment]
Effectively, I think we miss a dependency:

```
[velocity-mirror] Mirror is initializing...
SETUP GLOBALS

/home/maxime/.meteor/packages/meteor-tool/.1.0.38.18q8uit++os.linux.x86_64+web.browser+web.cordova/meteor-tool-os.linux.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:173
						throw(ex);
						      ^
ReferenceError: _ is not defined
    at moddedBindEnvironment (packages/mike:mocha/server.js:134:1)
    at global.it (packages/mike:mocha/server.js:208:1)
    at packages/velocity:test-proxy/tests/mocha/server/sampleServerTest.js:4:1
    at runWithEnvironment (packages/meteor/dynamics_nodejs.js:108:1)
    at Suite.<anonymous> (packages/meteor/dynamics_nodejs.js:121:1)
    at Object.context.describe.context.context (/home/maxime/.meteor/packages/mike_mocha/.0.5.1.1u9vs6w++os+web.browser+web.cordova/npm/node_modules/mocha/lib/interfaces/bdd.js:73:10)
    at global.describe (packages/mike:mocha/server.js:178:1)
    at Package (packages/velocity:test-proxy/tests/mocha/server/sampleServerTest.js:3:1)
    at Object.MochaWeb.testOnly (packages/mike:mocha/server.js:114:1)
    at Package (packages/velocity:test-proxy/tests/mocha/server/sampleServerTest.js:2:1)
```

**Comment by Sanjo** [comment]
underscore is missing as dependency in package.js in mike:mocha.
