### ISSUE TITLE
Errors running mocha

### ISSUE THREAD

**Issue by Tolmark12** [mad-eye/meteor-mocha-web#127]
I'm sure this must be an issue with my local machine, but can someone point me in the right direction of where to dig to root this issue out. When I try to run meteor mocha I get : 

```
W20150209-14:03:43.959(-7)? (STDERR) [velocity-mirror] /Users/Mark/.meteor/packages/meteor-tool/.1.0.40.959pzb++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/fibers.js:13
W20150209-14:03:43.960(-7)? (STDERR) 	throw new Error('`'+ modPath+ '.node` is missing. Try reinstalling `node-fibe
W20150209-14:03:43.960(-7)? (STDERR) 	      ^
W20150209-14:03:43.961(-7)? (STDERR) Error: `/Users/Mark/.meteor/packages/meteor-tool/.1.0.40.959pzb++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/bin/darwin-x64-v8-3.28/fibers.node` is missing. Try reinstalling `node-fibers`?
W20150209-14:03:43.961(-7)? (STDERR)     at Object.<anonymous> (/Users/Mark/.meteor/packages/meteor-tool/.1.0.40.959pzb++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/fibers.js:13:8)
W20150209-14:03:43.961(-7)? (STDERR)     at Module._compile (module.js:460:26)
W20150209-14:03:43.961(-7)? (STDERR)     at Object.Module._extensions..js (module.js:478:10)
W20150209-14:03:43.961(-7)? (STDERR)     at Module.load (module.js:355:32)
W20150209-14:03:43.961(-7)? (STDERR)     at Function.Module._load (module.js:310:12)
W20150209-14:03:43.961(-7)? (STDERR)     at Module.require (module.js:365:17)
W20150209-14:03:43.961(-7)? (STDERR)     at require (module.js:384:17)
W20150209-14:03:43.962(-7)? (STDERR)     at Object.<anonymous> (/Users/Mark/web/nano/.meteor/local/build/programs/server/boot.js:1:75)
W20150209-14:03:43.962(-7)? (STDERR)     at Module._compile (module.js:460:26)
W20150209-14:03:43.962(-7)? (STDERR)     at Object.Module._extensions..js (module.js:478:10)
W20150209-14:03:43.962(-7)? (STDERR) 

```

I've tried running velocity : jasmine which works fine, but really prefer mocha. Any ideas? Thanks!

**Comment by leebenson** [comment]
+1

**Comment by elmatrak** [comment]
This happened to me on my Mac when I upgrade node to 0.12 and upgraded all my packages. Still trying to figure out what happened and the solution.

**Comment by elmatrak** [comment]
I reverted back to 0.10.36 and it's working again, but then installing fibers picked up an existing installation in `~/.node` I wasn't aware of, I'll try upgrade over the weekend again but remove that folder next time.

**Comment by jhartma** [comment]
yep, same problem here with node 0.12

**Comment by rissem** [comment]
I just released a new version of mocha which does not use user's node, but the node which is bundled with Meteor. More info at https://github.com/mad-eye/meteor-mocha-web/issues/125

Please reopen if you're still having issues.

**Comment by Tolmark12** [comment]
Just tested and works great, thanks @rissem!
