### ISSUE TITLE
audit-argument-checks compatibility

### ISSUE THREAD

**Issue by matteodem** [mad-eye/meteor-mocha-web#129]
I get following error when I add ```mike:mocha``` as a package, which I think has to do with the mirror not checking all it's arguments (audit-argument-checks throws that error)

Exception while invoking method 'velocity/reports/submit' Error: Did not check() all arguments during call to 'velocity/reports/submit'

**Comment by sahkalit** [comment]
Yeah, having the same issue. Temporary  solutionis to remove audit-argument-checks.

**Comment by rissem** [comment]
Hmm it should be checked here https://github.com/meteor-velocity/velocity/blob/develop/core.js#L360-L372 but it's clearly not. Is there any more info in that error?

**Comment by rissem** [comment]
I am not seeing any issues with `mike:mocha@0.5.2`. Please reopen if you're still having issues.

**Comment by dpdonohue** [comment]
I am having this same issue using mike:mocha@0.5.4
I rolled back to mike:mocha@0.5.2 but still get the error:
```
I20150503-07:31:27.415(-4)? Exception while invoking method 'velocity/reports/submit' Error: Did not check() all arguments during call to 'velocity/reports/submit'
I20150503-07:31:27.415(-4)?     at [object Object]._.extend.throwUnlessAllArgumentsHaveBeenChecked (/Users/dd/ws/meteor/biologio/biolog/.meteor/local/build/programs/server/packages/check.js:375:13)
I20150503-07:31:27.415(-4)?     at Object.Match._failIfArgumentsAreNotAllChecked (/Users/dd/ws/meteor/biologio/biolog/.meteor/local/build/programs/server/packages/check.js:130:16)
I20150503-07:31:27.416(-4)?     at maybeAuditArgumentChecks (/Users/dd/ws/meteor/biologio/biolog/.meteor/local/build/programs/server/packages/ddp.js:2442:18)
I20150503-07:31:27.416(-4)?     at /Users/dd/ws/meteor/biologio/biolog/.meteor/local/build/programs/server/packages/ddp.js:1476:20
I20150503-07:31:27.416(-4)?     at [object Object]._.extend.withValue (/Users/dd/ws/meteor/biologio/biolog/.meteor/local/build/programs/server/packages/meteor.js:989:17)
I20150503-07:31:27.416(-4)?     at /Users/dd/ws/meteor/biologio/biolog/.meteor/local/build/programs/server/packages/ddp.js:1475:41
I20150503-07:31:27.416(-4)?     at [object Object]._.extend.withValue (/Users/dd/ws/meteor/biologio/biolog/.meteor/local/build/programs/server/packages/meteor.js:989:17)
I20150503-07:31:27.416(-4)?     at [object Object]._.extend.protocol_handlers.method (/Users/dd/ws/meteor/biologio/biolog/.meteor/local/build/programs/server/packages/ddp.js:1474:51)
I20150503-07:31:27.416(-4)?     at /Users/dd/ws/meteor/biologio/biolog/.meteor/local/build/programs/server/packages/ddp.js:1374:43
```

I also did this:
```meteor remove audit-argument-checks```
but tests no longer ran.
