### ISSUE TITLE
Unhandled 'error' event

### ISSUE THREAD

**Issue by Thomblin** [mad-eye/meteor-mocha-web#130]
Hi,

I am trying to add mike:mocha to a brand new meteor installation. However it fails every time. Details see below:

```
meteor --version
Meteor 1.0.3.1
```

```
meteor list  
meteor-platform  1.2.1  Include a standard set of Meteor packages in your app
mike:mocha       0.5.1  Run mocha tests in the browser
```

```
meteor   
[[[[[ /vagrant/dicerace ]]]]]                 

=> Started proxy.                             
=> Started MongoDB.                           
=> Started your app.                          

=> App running at: http://localhost:3000/
W20150212-20:51:25.357(0)? (STDERR) 
W20150212-20:51:25.359(0)? (STDERR) events.js:72
W20150212-20:51:25.359(0)? (STDERR)         throw er; // Unhandled 'error' event
W20150212-20:51:25.359(0)? (STDERR)               ^
W20150212-20:51:25.359(0)? (STDERR) Error: spawn ENOENT
W20150212-20:51:25.359(0)? (STDERR)     at errnoException (child_process.js:1001:11)
W20150212-20:51:25.359(0)? (STDERR)     at Process.ChildProcess._handle.onexit (child_process.js:792:34)
=> Exited with code: 8
```

**Comment by Thomblin** [comment]
well, no offend: meteor update fixed this, however i do not see a change in any package or meteor version :)

**Comment by rissem** [comment]
Closing for now. If you can produce a reliable reproduction path, please reopen. Thanks!
