### ISSUE TITLE
Error running tests: TypeError: undefined is not a function

### ISSUE THREAD

**Issue by rista404** [mad-eye/meteor-mocha-web#195]
Hey!

I inserted a few of the packages for testing my package:
```js
Package.onTest(function (api) {
	api.use("velocity:html-reporter");
	api.use("mike:mocha");
	api.use("practicalmeteor:chai");
	api.use("practicalmeteor:sinon");
        ....
```

When I run `meteor test-packages --port 8378 --settings settings.json --driver-package velocity:html-reporter` I get the following errors:

```sh
W20151114-13:37:24.487(1)? (STDERR)
W20151114-13:37:24.488(1)? (STDERR) /Users/user/.meteor/packages/meteor-tool/.1.1.10.m89grb++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:278
W20151114-13:37:24.488(1)? (STDERR) 						throw(ex);
W20151114-13:37:24.488(1)? (STDERR) 						      ^
W20151114-13:37:24.488(1)? (STDERR) TypeError: undefined is not a function
W20151114-13:37:24.488(1)? (STDERR)     at ddpParentConnection.call.framework (meteor://💻app/packages/mike_mocha/packages/mike_mocha.js:164:1)
W20151114-13:37:24.488(1)? (STDERR)     at /private/var/folders/k9/c9bvhqrd68x3vbs1_04mhbf80000gn/T/meteor-test-run8v2kqt/.meteor/local/build/programs/server/boot.js:249:5
=> Exited with code: 8
```

Has anyone experienced this or knows what's the problem?
Thanks!

**Comment by dmitrijs-balcers** [comment]
Try to specify latest package versions.
