### ISSUE TITLE
Meteor 1.3 beta React incompatibility ??

### ISSUE THREAD

**Issue by dagatsoin** [mad-eye/meteor-mocha-web#199]
Velocity Mocha does not start. I have this error:

```
tail -f /Users/vikti/dev/wizar-guide/.meteor/local/log/mocha.log

   While selecting package versions:
   error: Potentially incompatible change required to top-level dependency:
   react 0.14.3, was 0.14.3_1.
   Constraints on package "react":

   To allow potentially incompatible changes to top-level dependencies, you
   must pass --allow-incompatible-update on the command line.
```

I have also tried to launch via `meteor --allow-incompatible-update` 
I use Meteor 1.3.beta4 Any hint on this ?

**Comment by dagatsoin** [comment]
After upgrading on beta5, I have 

```
/Users/vikti/dev/wizar-guide/.meteor/local/mirrors/mocha/.meteor/local/build/programs/server/app/lib/collections.js:10
export { MapObjects };                                                 //
^^^^^^
SyntaxError: Unexpected reserved word
    at /Users/vikti/dev/wizar-guide/.meteor/local/mirrors/mocha/.meteor/local/build/programs/server/boot.js:241:30
    at Array.forEach (native)
    at Function._.each._.forEach (/Users/vikti/.meteor/packages/velocity_meteor-tool/.1.1.10_2.1incwsp++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/underscore/underscore.js:79:11)
    at /Users/vikti/dev/wizar-guide/.meteor/local/mirrors/mocha/.meteor/local/build/programs/server/boot.js:137:5
Exited with code: 8
Your application is crashing. Waiting for file change.
```

And collections.js is juste exporting a Mongo Collection in ES6 syntax

```
// lib/collections.js
export let MapObjects = new Mongo.Collection('mapObjects');
```

**Comment by dagatsoin** [comment]
way to old
